### ISSUE TITLE
We need a way to ensure a constant ignite version to use

### ISSUE THREAD

**Issue by lxgr-linux** [DecentralCardGame/Cardchain#101]
I propose this may be done, by introducing a wrapper that checks ignite version before running ignite itself and which ensures the correct ignite version is used.

**Comment by patrickwieth** [comment]
doesn't docker define the ignitehq/cli version?

**Comment by lxgr-linux** [comment]
No it's not and i isn't even ready yet. I will also incorporate #100 here.
