### ISSUE TITLE
ParameterChangeProposal  for cardchain param votingRightsExpirationTime failes

### ISSUE THREAD

**Issue by valNodeOne** [DecentralCardGame/Cardchain#115]
We tried to change the votingRightsExpirationTime paramter of the cardcahin module from 84000 to 100000 through a ParameterChangeProposal. The transaction failed with error code 111222 and condespace undefined (see tx details below).

A ParameterChangeProposal for airDropValue of the cardchain module was succesful though.

code: 111222
codespace: undefined
data: ""
events:
- attributes:
  - index: false
    key: ZmVl
    value: null
  type: tx
- attributes:
  - index: false
    key: YWNjX3NlcQ==
    value: Y2MxcHZ6NDdlcjc0bnM1bm0zeTV4dXF0cGRnMjdyYXJkdnV3NjZjanovMTI=
  type: tx
- attributes:
  - index: false
    key: c2lnbmF0dXJl
    value: TURhT3k5bTdIZlg4YXJLTU1waW9HS09weHVGUVFFMlQ4QUhYWEVzNVFTd1RhV1BOQ3dIaXBqQmlUcU1DWVJmZ0NkWGUxZU05L3ZBWlVGanlyZVlNakE9PQ==
  type: tx
gas_used: "40136"
gas_wanted: "200000"
height: "1890127"
info: ""
logs: []
raw_log: 'panic message redacted to hide potentially sensitive system info: panic'
timestamp: "2023-02-20T12:32:02Z"
tx:
  '@type': /cosmos.tx.v1beta1.Tx
  auth_info:
    fee:
      amount: []
      gas_limit: "200000"
      granter: ""
      payer: ""
    signer_infos:
    - mode_info:
        single:
          mode: SIGN_MODE_DIRECT
      public_key:
        '@type': /cosmos.crypto.secp256k1.PubKey
        key: A1KlTJEwnlbRxq5H66pEt1QzWHfi619ctXqr2PFU6MDy
      sequence: "12"
  body:
    extension_options: []
    memo: ""
    messages:
    - '@type': /cosmos.gov.v1beta1.MsgSubmitProposal
      content:
        '@type': /cosmos.params.v1beta1.ParameterChangeProposal
        changes:
        - key: votingRightsExpirationTime
          subspace: cardchain
          value: '"10000"'
        description: We want to change the votingRightsExpirationTime from 84000 to
          100000.
        title: 'Param change votingRightsExpirationTime: 100000'
      initial_deposit:
      - amount: "10"
        denom: ubpf
      proposer: cc1pvz47er74ns5nm3y5xuqtpdg27rardvuw66cjz
    non_critical_extension_options: []
    timeout_height: "0"
  signatures:
  - MDaOy9m7HfX8arKMMpioGKOpxuFQQE2T8AHXXEs5QSwTaWPNCwHipjBiTqMCYRfgCdXe1eM9/vAZUFjyreYMjA==
txhash: 49652D28013D2E6253255D153AD5EC66ACA054BC8038B9CCBD8C908DB6B1A470

**Comment by lxgr-linux** [comment]
Maybe you did send a string and not an int as the parameter value.

**Comment by lxgr-linux** [comment]
you have to capitalize `votingRightsExpirationTime` to `VotingRightsExpirationTime`

**Comment by patrickwieth** [comment]
omg this worked

**Comment by lxgr-linux** [comment]
Awesome
