### ISSUE TITLE
playable query

### ISSUE THREAD

**Issue by nlsui** [DecentralCardGame/Cardchain#209]
currently Status.playable includes all random cards in the gallery.
we need a query for cards from sets+starterdecks

**Comment by patrickwieth** [comment]
https://cardchain.crowdcontrol.network/cosmos/DecentralCardGame/Cardchain/cardchain/q_cards/playable?owner=&cardType=&classes=&sortBy=&nameContains=&keywordsContains=&notesContains=Finished

https://cardchain.crowdcontrol.network/cosmos/DecentralCardGame/Cardchain/cardchain/q_cards/playable?owner=&cardType=&classes=&sortBy=&nameContains=&keywordsContains=&notesContains=Starter

**Comment by lxgr-linux** [comment]
like patrick says, we already have queries for that, the notes contains does the trick. You could also alternatively query the alphaset `set` it self and read the cards from there.

**Comment by patrickwieth** [comment]
The alpha set does not contain the starter cards, so won't be of advantage in that regard. It can be of other use of course

**Comment by nlsui** [comment]
ok, thanks
