### ISSUE TITLE
lastCardModified on save card content

### ISSUE THREAD

**Issue by patrickwieth** [DecentralCardGame/Cardchain#212]
https://github.com/DecentralCardGame/Cardchain/blob/125b3fb6e8c7fce74c32eeaf3b4db6afc209abf3/x/cardchain/keeper/msg_server_save_card_content.go#L69

we need lastCardModifiedNow somewhere in this function, when a card is saved

**Comment by lxgr-linux** [comment]
Thats because in preparation for the council. Then only scheme cards can be edited.

**Comment by patrickwieth** [comment]
The problem is we have no council atm and when someone edits a card the changes do not arrive in the game
