### ISSUE TITLE
Card change hashing

### ISSUE THREAD

**Issue by patrickwieth** [DecentralCardGame/Cardchain#74]
put a hash onto a card that allows to check, if the image has changed

a hash method should be proposed to the game client guys and if it fits then we implement it

**Comment by lxgr-linux** [comment]
Have you talked to the gameclient people?
If so, I would suggest either adding this to the get_card_content query or split of the the image query from the get_card query, so get_card returns all card date BUT the image it self.
The image then could be queried via a get_image query.
