### ISSUE TITLE
Booster Pack as transferable item

### ISSUE THREAD

**Issue by patrickwieth** [DecentralCardGame/Cardchain#78]
It makes sense to have booster packs as transferable items, so you can theoretically buy a pack, transfer it to someone and he/she opens it. You can also store a booster pack then over a long time and open it later or use it as a reward in a tournament etc.

**Comment by lxgr-linux** [comment]
I will add this

**Comment by lxgr-linux** [comment]
this may be problematic with how boosterpacks work.
The contributors to a boosterpack are rewarded when the boosterpack is opened and their card is part of the pack. But with this approach boosterpacks can be paid way before they are opened, which means paiment can't be determined at paytime, but at opentime.

This can be resolved by using an payment pool on the transferable item it self, which is emptied on opening but filled at paytime

**Comment by lxgr-linux** [comment]
lol never mind

**Comment by patrickwieth** [comment]
actually a sold boosterpack gives yield to everyone who contributed and not only the ones whose cards were in the pack (this is why you said lol never mind?)

**Comment by lxgr-linux** [comment]
yes
