### ISSUE TITLE
Errors from cardobject are not chained through the API 

### ISSUE THREAD

**Issue by patrickwieth** [DecentralCardGame/Cardchain#82]
If the cardobject rejects a card, then there is only this info in the tx:

"codespace": "undefined",
    "code": 1,
    "data": "",
    "raw_log": "internal",
    
which does not really help

A reason why this is not showing the error message from the cardobject might be, that the error is not properly registered:
Register Error https://docs.cosmos.network/master/building-modules/errors.html

We should check if this behavior changes if we properly register the error

**Comment by lxgr-linux** [comment]
I will look into that.
