### ISSUE TITLE
lastCardChange

### ISSUE THREAD

**Issue by patrickwieth** [DecentralCardGame/Cardchain#95]
we should save a variable that stores when the content of a card was changed

so whenever a card gets banned or saveCardContent changes the content, this variable should be set to the current block height

this allows the gameclient to see if it has the most recent card set, or has to update stuff

the variable should be accessible via q-cardchain-info

**Comment by lxgr-linux** [comment]
Why would this be relevant to access via q-cardchain-info?
How I understood it, this variable would be a attribute of the `Card` type and therefore different for every card. Did you maybe mean `q_card`?

**Comment by patrickwieth** [comment]
No, this is global. Without it the gameclient must poll all card content every 10s and see if there are changes, with this feature only 1 query must be done and when a card has changed, the new cards can be queried.
So we already have a image hash on q_card_content but we don't know if any card has changed...

**Comment by lxgr-linux** [comment]
Cases for setting this:
- Card suspended
- Card banned
- Card nerfed/buffed
- Make card playable (council)

More @patrickwieth @nlsui
